/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Day9.ConnectDatabase.StockExchange.View.Admin;

import Day9.ConnectDatabase.StockExchange.Model.Trader;
import Day9.ConnectDatabase.StockExchange.Service.RegisterService;
import javax.swing.JOptionPane;

/**
 *
 * @author NguyenHieu
 */
public class AddTraderView extends javax.swing.JFrame {

    /**
     * Creates new form AddTraderView
     */
    Trader trader ;
    public AddTraderView(Trader trader) {
        initComponents();
        this.trader = trader;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_gmail = new javax.swing.JTextField();
        spn_money = new javax.swing.JSpinner();
        tbn_addTrader = new javax.swing.JButton();
        lbl_errorName = new javax.swing.JLabel();
        lbl_errorAddress = new javax.swing.JLabel();
        lbl_errorGmail = new javax.swing.JLabel();
        lbl_errorMoney = new javax.swing.JLabel();
        lbl_error = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm người dùng");

        jLabel1.setText("THÊM NGƯỜI DÙNG");

        jLabel2.setText("Tên người dùng");

        jLabel3.setText("Địa chỉ");

        jLabel4.setText("Gmail");

        jLabel5.setText("Số tiền trong TK");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        tbn_addTrader.setText("Xác nhận");
        tbn_addTrader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_addTraderActionPerformed(evt);
            }
        });

        lbl_errorName.setForeground(new java.awt.Color(255, 0, 0));

        lbl_errorAddress.setForeground(new java.awt.Color(255, 0, 0));

        lbl_errorGmail.setForeground(new java.awt.Color(255, 0, 0));

        lbl_errorMoney.setForeground(new java.awt.Color(255, 0, 51));

        lbl_error.setForeground(new java.awt.Color(255, 0, 0));

        btn_back.setText("Trở lại");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_errorMoney)
                            .addComponent(lbl_errorGmail)
                            .addComponent(lbl_errorAddress)
                            .addComponent(lbl_errorName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbn_addTrader)
                                .addGap(18, 18, 18)
                                .addComponent(btn_back))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(txt_name)
                                .addComponent(txt_address)
                                .addComponent(txt_gmail)
                                .addComponent(spn_money, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lbl_error)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(lbl_error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_errorName)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lbl_errorAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_errorGmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spn_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_errorMoney)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbn_addTrader)
                    .addComponent(btn_back))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void tbn_addTraderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_addTraderActionPerformed
        if(txt_name.getText().equals("")) lbl_errorName.setText("Không được để trống");
        else lbl_errorName.setText("");
        if(txt_gmail.getText().equals("")) lbl_errorGmail.setText("Không được để trống");
        else lbl_errorGmail.setText("");
        if((Integer)spn_money.getValue() < 0) lbl_errorMoney.setText("Không hợp lệ");
        else lbl_errorMoney.setText("");
        if(txt_address.getText().equals("")) lbl_errorAddress.setText("Không được để trống");
        else lbl_errorAddress.setText("");
        if(!txt_name.getText().equals("")
            && !txt_gmail.getText().equals("")
            && (Integer)spn_money.getValue() >= 0
            && !txt_address.getText().equals("")
            ){
            RegisterService registerService = new RegisterService();
            if(!registerService.register(txt_name.getText(), "123456", txt_address.getText(), txt_gmail.getText(), (Integer)spn_money.getValue())){
                lbl_error.setText("Người dùng đã tồn tại!!!");
            }else{
                JOptionPane.showMessageDialog(this,"Thêm người dùng thành công");
                new HomeAdminView(trader).setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_tbn_addTraderActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new HomeAdminView(trader).show();
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTraderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTraderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTraderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTraderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AddTraderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_errorAddress;
    private javax.swing.JLabel lbl_errorGmail;
    private javax.swing.JLabel lbl_errorMoney;
    private javax.swing.JLabel lbl_errorName;
    private javax.swing.JSpinner spn_money;
    private javax.swing.JButton tbn_addTrader;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_gmail;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
